const fs=require('fs'),vm=require('vm'),test=require('node:test'),assert=require('node:assert/strict');
const s=fs.readFileSync(__dirname+'/../app.js','utf8');
function section(a,b){return s.slice(s.indexOf(a),s.indexOf(b,s.indexOf(a)));}
function setup(){const elements={'shifts-list':{children:[{dataset:{reportDate:'2026-10-05'}}]}},cached=[],highlights=[];const c={state:{code:'a',currentMonth:new Date(2026,9,1),shifts:[{dateStr:'2026-10-05',hours:2},{dateStr:'2026-10-06',hours:24}]},monthSync:{revision:'old',dayRevisions:{}},monthKeyOf:()=> '2026-10',monthLoadSequence:5,apiReadsInFlight:new Map(),saveMonthToCache:(k,rows)=>cached.push(rows),setMonthSync(){},renderShifts:verified=>assert.equal(verified,false),renderStatsBreakdown(){},$:id=>elements[id]||(elements[id]={}),decorateHoursSavedCard:(card,shift,verified)=>highlights.push({shift,verified})};vm.createContext(c);vm.runInContext(section('function applyConfirmedHoursMutation(', 'async function refreshMonthKeepingSelection('),c);return{c,cached,highlights};}
const params={code:'a',dateStr:'2026-10-05'},result={success:true,monthKey:'2026-10',shift:{dateStr:'2026-10-05',hours:26,startTime:'05:00',endTime:'07:00'}};
test('server-confirmed row appears immediately without another API request; other days preserved',()=>{const f=setup();assert.equal(f.c.applyConfirmedHoursMutation(params,result),true);assert.equal(f.c.state.shifts[0].hours,26);assert.equal(f.c.state.shifts[1].hours,24);assert.equal(f.c.monthSync.revision,null);assert.equal(f.c.monthLoadSequence,6);assert.equal(f.highlights[0].verified,true);});
test('failed, malformed, other account or other month response never modifies screen',()=>{for(const r of [null,{...result,success:false},{...result,shift:null},{...result,monthKey:'2026-09'},{...result,shift:{dateStr:params.dateStr,hours:NaN}}]){const f=setup();assert.equal(f.c.applyConfirmedHoursMutation(params,r),false);assert.equal(f.cached.length,0);}const f=setup();f.c.state.code='b';assert.equal(f.c.applyConfirmedHoursMutation(params,result),false);});
test('confirmed deletion removes only the selected day',()=>{const f=setup();assert.equal(f.c.applyConfirmedHoursMutation(params,{success:true,monthKey:'2026-10',deletedDate:params.dateStr}),true);assert.equal(f.c.state.shifts.length,1);assert.equal(f.c.state.shifts[0].dateStr,'2026-10-06');});
test('bundled login month renders before extras with no duplicate hours request',async()=>{let resolve;const calls=[],renders=[];const c={state:{code:'a',currentMonth:new Date()},monthLoadSequence:0,monthKeyOf:()=> '2026-10',apiGet:async(a,p)=>{calls.push(p.section);return new Promise(r=>resolve=r);},monthSync:{},saveMonthToCache(){},renderShifts:()=>renders.push(true),renderStatsBreakdown(){},$:()=>({}),setMonthSync(){},showToast(){}};vm.createContext(c);vm.runInContext(section('async function loadBootstrap(', '// ====================================================================='),c);const promise=c.loadBootstrap(true,{success:true,monthKey:'2026-10',shifts:[{dateStr:'2026-10-05',hours:26}]});assert.deepEqual(calls,['extras']);assert.equal(renders.length,1);resolve({});await promise;});

